import { FC } from 'react';
import { DetailedAnalysis } from '../types';
import { X, Printer, Download, ShieldCheck } from 'lucide-react';

export const ReportModal: FC<{ doc: DetailedAnalysis; onClose: () => void }> = ({ doc, onClose }) => {
  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-3xl overflow-hidden shadow-2xl my-8">
        <div className="p-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-cyan-400" />
            <span className="text-sm font-bold text-white">Forensic Verification Dossier Report</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="p-1.5 text-slate-400 hover:text-white rounded bg-slate-800"
            >
              <Printer className="w-4 h-4" />
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-white rounded bg-slate-800"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        <div className="p-8 bg-slate-950 text-slate-200 text-xs space-y-6 font-sans">
          <div className="flex justify-between items-start border-b border-slate-800 pb-4">
            <div>
              <h1 className="text-xl font-black tracking-wider text-white">IDSHIELD AI</h1>
              <p className="text-[11px] text-slate-400">National Fraud Detection & Document Verification Unit</p>
              <p className="text-[10px] font-mono text-slate-500 mt-1">Audit Key: {doc.id} // SHA-256 Validated</p>
            </div>
            <div className="text-right">
              <div className="text-sm font-bold text-rose-400 uppercase tracking-wide">VERDICT: SUSPICIOUS</div>
              <div className="text-[10px] text-slate-400">{doc.timestamp}</div>
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-3 bg-slate-900/90 rounded border border-slate-800">
            <div>
              <span className="text-[10px] text-slate-500 block uppercase">Document Type</span>
              <span className="font-bold text-white">{doc.docType}</span>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 block uppercase">Subject Identifier</span>
              <span className="font-mono font-bold text-slate-300">{doc.subjectMaskedId}</span>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 block uppercase">Risk Index</span>
              <span className="font-bold text-rose-400">{doc.riskScore} / 100</span>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 block uppercase">Tampering Status</span>
              <span className="font-bold text-rose-400">POSITIVE</span>
            </div>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold text-slate-300 text-xs uppercase tracking-wider border-b border-slate-800 pb-1">
              Forensic Findings & Detected Anomalies
            </h3>
            <div className="space-y-2">
              {doc.evidenceRegions.map((ev, idx) => (
                <div key={idx} className="p-2.5 rounded bg-slate-900 border border-slate-800 flex justify-between items-start">
                  <div>
                    <span className="font-bold text-slate-200 block">{ev.label}</span>
                    <span className="text-[11px] text-slate-400">{ev.explanation}</span>
                  </div>
                  <span className="font-mono text-rose-400 font-bold ml-4 whitespace-nowrap">
                    {ev.confidence}% Confidence
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold text-slate-300 text-xs uppercase tracking-wider border-b border-slate-800 pb-1">
              Neural Engine Rationale
            </h3>
            <ul className="list-disc list-inside space-y-1 text-[11px] text-slate-400">
              {doc.aiExplanation.map((line, i) => (
                <li key={i}>{line}</li>
              ))}
            </ul>
          </div>

          <div className="pt-6 border-t border-slate-800 flex justify-between items-end text-[10px] text-slate-500 font-mono">
            <div>
              <div>Generated by IDSHIELD AI Autonomous Screening Pipeline</div>
              <div>Node: {doc.processedByNode}</div>
            </div>
            <div className="text-right">
              <div className="text-slate-300 font-bold uppercase">Authorized Investigative Signoff</div>
              <div className="mt-1 text-slate-600">ELECTRONICALLY SIGNED & ENCRYPTED</div>
            </div>
          </div>
        </div>

        <div className="p-4 bg-slate-950 border-t border-slate-800 flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-slate-400 hover:text-white"
          >
            Close Preview
          </button>
          <button
            onClick={() => window.print()}
            className="px-4 py-2 text-xs font-bold bg-cyan-500 hover:bg-cyan-400 text-slate-950 rounded-lg flex items-center gap-1.5 transition"
          >
            <Download className="w-4 h-4" /> Download Certified PDF
          </button>
        </div>
      </div>
    </div>
  );
};